version: '2.1'

services:

  springBoot:
    image: spring-boot-elk/spring-boot:latest
    hostname: springBoot
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 && echo 'cool, it works'"]
      interval: 2m30s
      timeout: 10s
      retries: 5
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    volumes:
      - ./logs:/deployments/logs
    logging:
       driver: "json-file"
       options:
         max-file: "15"
         max-size: "50m"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
       - cluster.name=docker-cluster
       - bootstrap.memory_lock=true
       - xpack.security.enabled=false
       - discovery.type=single-node
       - discovery.zen.minimum_master_nodes=1
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 2g
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.2
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
     - ./logstash_config:/etc/logstash/conf.d
    ports:
     - "5000:5000"
    links:
     - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    container_name: kibana
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
     - "5601:5601"
    links:
     - elasticsearch

volumes:
  esdata1:
      driver: local
